### ISSUE TITLE
seg fault for LSTM on CUDA 9.0 and CUDA 8.0 with CUDNN 7.1.1.

### ISSUE THREAD

**Issue by osofr** [JuliaGPU/CuArrays.jl#57] opened 2018-03-13 22:20 UTC
I get the following error, after many prediction queries to flux-based LSTM. This is an error on CUDA 9.0. The error on CUDA 8.0 is similar, but it relates to garbage collection (when calling `free`). Does it makes sense? Is the source of the error obvious and is it easily fixable? I could try to work on replicable example, but its pretty difficult as I am not sure exactly what triggers the error (very large code base involved). My guess is that its garbage collection.

Just to clarify a bit, this error *never* occurs when training LSTM. Only when doing inference with LSTM, where the SGD is being performed for a vector of parameter (unrelated to LSTM). The predictions from LSTM are used to define the loss. Prior to running this SGD on GPU, the LSTM is "untracked" with `mTᵏ = Flux.mapleaves(Flux.Tracker.data, mTᵏ)`. The whole procedure runs fine on CPUs. Is this `CuArrays` issue or `Flux` issue? Anything I can do to further diagnose? Much appreciated!

```julia
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
cfree at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
cudnnDestroyTensorDescriptor at /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.1 (unknown line)
unknown function (ip: 0x7f2dd8194a55)
cudnnRNNBackwardData at /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.1 (unknown line)
macro expansion at /home/ubuntu/.julia/v0.6/CuArrays/src/dnn/error.jl:17 [inlined]
cudnnRNNBackwardData at /home/ubuntu/.julia/v0.6/Flux/src/cuda/cudnn.jl:189
unknown function (ip: 0x7f2dfc1c217b)
jl_call_fptr_internal at /usr/local/src/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /usr/local/src/julia/src/julia_internal.h:358 [inlined]
jl_invoke at /usr/local/src/julia/src/gf.c:41
backwardData at /home/ubuntu/.julia/v0.6/Flux/src/cuda/cudnn.jl:206
unknown function (ip: 0x7f2dfc1c12e0)
jl_call_fptr_internal at /usr/local/src/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /usr/local/src/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /usr/local/src/julia/src/gf.c:1926
back_ at /home/ubuntu/.julia/v0.6/Flux/src/cuda/cudnn.jl:363
back_ at /home/ubuntu/.julia/v0.6/Flux/src/tracker/back.jl:25
unknown function (ip: 0x7f2dfc1c077d)
```

**Comment by maleadt** [comment] 2018-10-05 05:48
Pretty late response, but only working my way through the tracker now. This would be pretty hard to debug without a reproducer. Furthermore, it looks like Flux is calling CUDNN directly here: https://github.com/FluxML/Flux.jl/blob/86683e5991b86808b3b721419da5ab122d2bf846/src/cuda/cudnn.jl#L191-L216 (as part of your backtrace). This functionality probably should move to CuArrays (@MikeInnes?). But in the meantime, it would be a bug in Flux, and not CuArrays, so I'm closing this.

**Closed by maleadt** 2018-10-05 05:48 UTC
Labels: bug
