### ISSUE TITLE
Fail to precompile CuArrays

### ISSUE THREAD

**Issue by wenquan** [JuliaGPU/CuArrays.jl#329] opened 2019-04-27 11:10 UTC
```
[ Info: Precompiling CuArrays [3a865a2d-5b23-5a0f-bc46-62713ec82fae]
WARNING: could not import NNlib.spatial_dims into CUDNN
ERROR: LoadError: LoadError: LoadError: UndefVarError: DenseConvDims not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /ghome/wenquan/.julia/packages/CuArrays/PwSdF/src/dnn/CUDNN.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include at ./sysimg.jl:29 [inlined]
 [10] include(::String) at /ghome/wenquan/.julia/packages/CuArrays/PwSdF/src/CuArrays.jl:3
 [11] top-level scope at none:0
 [12] include at ./boot.jl:326 [inlined]
 [13] include_relative(::Module, ::String) at ./loading.jl:1038
 [14] include(::Module, ::String) at ./sysimg.jl:29
 [15] top-level scope at none:2
 [16] eval at ./boot.jl:328 [inlined]
 [17] eval(::Expr) at ./client.jl:404
 [18] top-level scope at ./none:3
in expression starting at /ghome/wenquan/.julia/packages/CuArrays/PwSdF/src/dnn/libcudnn.jl:265
in expression starting at /ghome/wenquan/.julia/packages/CuArrays/PwSdF/src/dnn/CUDNN.jl:35
in expression starting at /ghome/wenquan/.julia/packages/CuArrays/PwSdF/src/CuArrays.jl:52
```
Not sure what is the problem here.

**Comment by ali-ramadhan** [comment] 2019-04-27 11:42
This may be a duplicate of https://github.com/JuliaGPU/CuArrays.jl/issues/327

If you're not using Flux.jl, `] add NNlib#master` worked for me as a temporary fix.

**Comment by maleadt** [comment] 2019-04-27 18:16
Yeah, dup of #327.

**Closed by maleadt** 2019-04-27 18:16 UTC
Labels: bug
