### ISSUE TITLE
Horrible performance for "x[i,:] = vec" bottlenecks "back(::typeof(getindex),..)" in Flux.

### ISSUE THREAD

**Issue by osofr** [JuliaGPU/CuArrays.jl#77] opened 2018-05-02 01:10 UTC
My `Flux` code is taking 10-50x times longer to run on top GPU (Tesla V100) compared to an old CPU. There is also a Flux [issue](https://github.com/FluxML/Flux.jl/issues/189) open for this, but the problem is actually with `CuArrays` as demonstrated below.

The problem is in [2nd line](https://github.com/FluxML/Flux.jl/blob/5efbaddb974be3d05fa08df18496f5f14c7cc2a1/src/tracker/array.jl#L67) of `Flux.back`:
```julia
function back(::typeof(getindex), Δ, xs::Flux.TrackedArray, i...)
  Δ′ = zeros(xs.data)
  Δ′[i...] = Δ
  Flux.Tracker.@back(xs, Δ′)
end
```

This kills performance on GPUs. Is there any temporary workaround for this? Our code relies heavy on doing something like this `out = [out[i,:] for i=1:(3*nparams)]` in advance, as part of inference. So we can't avoid this type of indexing (I really tried to avoid it!!!). Any bandaid solution, anything? We only need `back` to work for indices of the type `out[i,:]`. 
We are trying to wrap up a project that has become solely dependent on Flux at this point. We are completely stuck, as effectively our Flux code is completely unsuitable for GPUs. Its also impossible for us to finish this project with CPUs.  Would it be possible to help us? Please?  Any advice would be highly appreciated!

Here is an example that highlights the performance hit and the type of indexing that we need. 

Please note that its **much**  faster to **copy the array to cpu, do the `setindex!`, then copy back to GPU**!!!. This is shown below in `back_hack`. There's got to be a more performant GPU-only solution, no???

```julia
julia> using Flux
julia> using CuArrays
julia> testx = rand(2,100);
julia> x = param(testx);
julia> idx = (1,:); # (1, Colon())
julia> l = Flux.getindex(x,idx...);
julia> l2 = sum(l);
julia> @time Flux.back!(l2);
  0.000010 seconds (9 allocations: 2.844 KiB)
julia> xg = param(testx) |> gpu;
julia> l = Flux.getindex(xg,idx...);
julia> l2 = sum(l);
julia> @time Flux.back!(l2);
  0.044698 seconds (1.77 k allocations: 86.266 KiB)
```

Here is comparison to CPU version:

```julia
function back(::typeof(getindex), Δ, xs::Flux.TrackedArray, i...)
  Δ′ = zeros(xs.data)
  Δ′[i...] = Δ
  Flux.Tracker.@back(xs, Δ′)
end

function back_hack(::typeof(getindex), Δ, xs::Flux.TrackedArray, i...)
  Δ′ = zeros(xs.data|>cpu)
  Δ′[i...] = (Δ|>cpu)
  Flux.Tracker.@back(xs, Δ′|>gpu)
end

## directly call back
## ON CPU:
@time back(getindex, Flux.Tracker.grad(x)[1,1:100], x, idx...)
# 0.000019 seconds (11 allocations: 2.922 KiB)

## ON GPU
@time back(getindex, Flux.Tracker.grad(xg)[1,1:100], xg, idx...)
# 0.030649 seconds (1.78 k allocations: 86.656 KiB)

## even moving to CPU then back to GPU is doing better:
@time back_hack(getindex, Flux.Tracker.grad(xg)[1,1:100], xg, idx...)
# 0.000290 seconds (97 allocations: 6.297 KiB)

# Note that the entire run time is dominated by setindex!
xg = rand(2,100) |> gpu;
repl = zeros(100) |> gpu;
@time xg[1,:] = repl;
# 0.030225 seconds (1.71 k allocations: 84.547 KiB)
```

**Comment by MikeInnes** [comment] 2018-05-02 09:14
Hey @osofr, I will take a look at this today and see what I can do. The egregiousness of the performance hit is actually a good thing here, because something very simple has gone wrong; most likely a kernel just slipped through the cracks.

So just to clarify, the slowdown caused by a statement of the form `x[i,:] = ...`, right, but the forward pass `x[i,:]` is fine? Is this call falling back to scalar indexing (it will error if you call `CuArrays.allowscalar(false)` beforehand)?

**Comment by osofr** [comment] 2018-05-02 16:04
Thank you so much @MikeInnes! Yes, this is exactly right. The forward pass is fine and is much faster on GPU. It errors out when setting `CuArrays.allowscalar(false)`, at least the last example below. I haven't checked if it will also error out when calling `back`, but I am fairly certain this is the case. Thank you so much for your help! I wish I knew how to fix this myself, will hopefully learn something from your fix. 

```julia
xg = rand(2,100) |> gpu;
repl = zeros(100) |> gpu;
@time xg[1,:] = repl;
```

**Comment by MikeInnes** [comment] 2018-05-02 16:12
Ok, so this is happening just because we don't have a setindex kernel on the GPU; pinging @SimonDanisch who can hopefully implement one in GPUArrays fairly quickly.

**Comment by osofr** [comment] 2018-05-02 16:46
Ok, thanks!

@SimonDanisch, anything I can do to expedite this? Can this kernel be borrowed from somewhere? Am I the first person to try to overwrite a row/column in GPU array?

**Comment by MikeInnes** [comment] 2018-05-02 17:31
Can you try `Pkg.update()`? Looks like this was fixed on master and just not tagged yet.

**Comment by osofr** [comment] 2018-05-02 17:36
Ok, fairly certain I tried this yesterday, but will do so right now. Just to confirm, I should update `GPUArrays`? Will take me a few minutes to spin up GPU instance, but will get back shortly.

**Comment by MikeInnes** [comment] 2018-05-02 18:01
Yeah, GPUArrays has the fix. If not, would be useful to narrow down what the `setindex` is being called with.

**Comment by osofr** [comment] 2018-05-02 18:10
Woohoo, it works! Not as fast as CPU, but it will do. I will re-run my Flux training code, just to confirm that the performance has improved and will close the issue then. Just out of curiosity, would you mind pointing me to the `GPUArrays` commit that fixes this setindex issue? I'd like to understand it for future hacking. Thank you so much @MikeInnes! 

```julia
julia> using Flux, CuArrays
julia> testx = rand(2,100);
julia> x = param(testx);
julia> idx = (1,:); # (1, Colon())
julia> l = Flux.getindex(x,idx...);
julia> l2 = sum(l);
julia> Flux.back!(l2);
julia> @time Flux.back!(l2);
  0.000011 seconds (9 allocations: 2.844 KiB)

julia> xg = param(testx) |> gpu;
julia> l = Flux.getindex(xg,idx...);
julia> l2 = sum(l);
julia> Flux.back!(l2);
julia> @time Flux.back!(l2);
  0.000246 seconds (104 allocations: 2.844 KiB)
```

**Closed** 2018-05-02 21:54 UTC

**Comment by MikeInnes** [comment] 2018-05-03 11:57
I think you're just timing kernel launch overhead there, which is significant when the size of the array is small. Hopefully the times for the overall model are much better.

[Here's](https://github.com/JuliaGPU/GPUArrays.jl/blob/1bb4cabd8ec7672b1cdd31648073d15ac1966341/src/indexing.jl#L67) the GPU code for `setindex!`. Hacking on GPU kernels in Julia is pretty easy and straightforward now, so I'd definitely recommend playing around with it, maybe via CUDAnative.
